app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    """
    Function that queries the database and gets a user with the id

    Args:
        UserId:The id of the specific user
    """
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    """
    User model class

    Args:
        DbModel:Connects our class to our database and allow communication
    """
    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        """
        Method to create a write only class property
        """
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        """
        Method to set the password
        """
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        """
        Method that takes in a password,hashes it and compares it to the hashed password for verification
        """
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        """
        Function that makes debugging easier
        """
        return f'User {self.username}'

class Role(db.Model):
    """
    Class that will define all different roles

    Args:
        DbModel:Connects our class to our database and allow communication
    """
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        """
        Function that makes debugging easier
        """
        return f'User {self.name}'

class Blog(db.Model):
    """
    Class that handles blog post requests

    Args:
        DbModel:Connects our class to our database and allow communication
    """
    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    blog_id = db.Column(db.Integer)
    blog_title = db.Column(db.String)
    blog_subject = db.Column(db.String)
    posted = db.Column(db.DateTime,default = datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_blog(self):
        """
        Method to save the blogs
        """
        db.session.add(self)
        db.session.commit()

class RandQuote():
    """
    Class to display random quotes
    """

    def __init__(self,author,quote,permalink):
        self.author = author
        self.quote = quote
        self.permalink = permalink




    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    """
    Class for users to write their own blogs
    """

    title = StringField('Blog title',validators=[Required()])
    blog = TextAreaField('Write a new blog')
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    """
    Class to update our profile
    """
    bio = TextAreaField('Tell us about you.',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
# Import extensions
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_uploads import UploadSet,configure_uploads,IMAGES

# Create extension instances
app = Flask(__name__)
bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)



def create_app(config_name):
    """
    Function that handles all extensions and blueprints

    Args:
        ConfigName:
    """

    # Setting up app configurations
    app.config.from_object(config_options[config_name])
    
    # Initialize flask extensions
    db.init_app(app)
    bootstrap.init_app(app)
    configure_uploads(app,photos)
    login_manager.init_app(app)
    

    # Import app blueprints
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    # Register app blueprints
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)



    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import User,Blog
from .forms import BlogForm,UpdateProfile
from .. import db,photos
from ..requests import get_quote



@main.route('/')
def index():
    """
    View root page function that returns the index page
    """
    new = Blog.query.all()
    return render_template('index.html',new = new)
    

@main.route('/user/<uname>')
def profile(uname):
    """
    Function to render the profile page
    """
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    """
    View function to handle update profile request

    Args:
        Uname:The users username
    """
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    """
    Function to allow update of profile photo
    """
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/')
def blog(id):
    """
    Function to find blog
    """
    blogs = Blog.query.filter_by(id)

    return render_template('index.html', blogs=blogs)



@main.route('/blog/new',methods = ['GET','POST'])
def new_blog():
    new = BlogForm()

    if new.validate_on_submit():

        brand = Blog(blog_title = new.title.data,blog_subject = new.blog.data)

        brand.save_blog()

        return redirect(url_for('main.index'))

    title = 'New Blog'
    return render_template('blog.html',title = title,new = new)

@main.route('/random_quote')
def random_quote():
    """
    Function to display random quotes
    """
    quote = get_quote()
    return render_template('quote.html',quote = quote)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
 {{super()}}
 <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
 <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
{% endblock %}


{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/js/mdb.min.js"></script> -->
{% endblock %}

app/templates/blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1>New Blog</h1>
                    {{wtf.quick_form(new)}}
                </div>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
</body>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<body>
	<div class="container">
		<hr>
		<h1><center>LET'S BLOG</center></h1>
		<hr>
		<style>
			h1{
				color:blue;
				font-family:cursive;
				font-size:50px;
			}
		</style>
		<div class="buttons">
			{% if current_user.is_authenticated %}
			<button class = 'btn btn-lg btn btn-info' ><a href = '/blog/new' >Start blogging</a></button>
			<button class = 'btn btn-lg btn btn-success'  ><a href = '/random_quote' >Show quote</a></button>
			{% else %}
			<button class = 'btn btn-lg btn btn-info' ><a href = '{{url_for('auth.register')}}' >Sign up</a></button>
			<button class = 'btn btn-lg btn btn-success'  ><a href = '{{url_for('auth.login')}}' >Sign in</a></button>
			{% endif %}
			<style>
				.buttons{
					align-items:center;
					margin-left:430px;
				}
			</style>
		</div>
	</div>
</body>
{% endblock %}

app/templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">
  
  <!-- Navbar brand -->
  <a class="navbar-brand" href="#">Navbar</a>
  
  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
  aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<!-- Collapsible content -->
<div class="collapse navbar-collapse" id="basicExampleNav">
  <!-- <h1><center>Blogs</center></h1> -->
  <!-- Links -->
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="{{url_for('main.index')}}">Home
        <span class="sr-only">(current)</span>
      </a>
    </li>
    {% if current_user.is_authenticated %}
    <li><a class = 'nav-link' href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
    <li class="nav-item">
      <a class = 'nav-link' href="{{url_for('auth.logout')}}">Sign out</a>
    </li>
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{{url_for('auth.login')}}">Sign In</a>
    </li>
    {% endif %}
  </div>
  <!-- Collapsible content -->
  
</nav>
<!--/.Navbar-->

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying username -->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>
            <!-- Displaying user bio -->
            {% if user.bio %}
            <p> {{user.bio}} </p>
            {% else %}
            <p> {{user.username | capitalize}} has no bio </p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
        </div>
        <!-- Displaying profile photo -->
        <div class="col-md-4">
            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <p>No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
              <input type="file" name="photo" class="form-control" required>
              <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/quote.html
{% extends 'base.html' %}

{% block content %}
<body>
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <blockquote>
                <h1>{{quote.author}}</h1>
                <br>
                <p> >> {{quote.quote}}</p>
            </blockquote>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
</body>
{% endblock %}